puts "The students of MAcademy"
puts "---------------"
puts "Dr. Hannibal Lecter"
puts "Darth Veder"
puts "Nurse Rached"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Normal Bates"
